export * from './Inicio'
export * from './Notificaciones'
export * from './Perfil'
export * from './Reportes'
export * from './MyProfile'
export * from './Reportar_Problema'
export * from './VerNoticias'
